<?php

namespace Database\Seeders;

use App\Models\Source;
use App\Models\SourceColumnMapping;
use Illuminate\Database\Seeder;

/**
 * Seeds the column mappings for ALPHA/BNA/WEB/SMT/STEG from the client's
 * validated rules (2026-07):
 *
 *   - WEB (alias STEG) : reference = 9 rightmost digits of the fused
 *     "session,reference" column; secondary_reference = recu_paie (with
 *     conditional b/B prefix stripped + zero-padded to 6 to align with
 *     BNA's N° autorisation); montant; date_paiement.
 *   - BNA : num_autorisation (N° autorisation, zero-padded 6);
 *     Montant (TND); Date; Type de la transaction.
 *   - ALPHA : num_autorisation (NUM_AUTO, b/B stripped + zero-padded 6);
 *     reference (REFERENCE, zero-padded 9); MONTANT_ENCAISS; DAT_ENC;
 *     CANAL.
 *   - SMT : ONLY date (New Deposit date) + amount (Montant) — every other
 *     field is intentionally removed per client spec. Matching against
 *     other sources uses the composite date|amount key generated by
 *     TransactionNormalizer.
 *   - STEG : same file structure as WEB (client: "STEG (nommé aussi WEB)").
 *
 * The client confirmed the WEB file has a single fused column literally
 * named "session,reference" whose cell contains session+référence — the
 * reference is the 9 rightmost digits of that cell.
 */
class SourceColumnMappingSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedAlpha();
        $this->seedBna();
        $this->seedWeb();
        $this->seedSmt();
        $this->seedSteg();
    }

    private function seedAlpha(): void
    {
        $source = Source::query()->where('code', 'ALPHA')->firstOrFail();

        // NUM_AUTO is the cross-source matching key (N° autorisation) — it
        // must be named num_autorisation internally, not reference.
        // Zero-padded to 6 to match BNA's N° autorisation (also 6-digit,
        // zero-padded) for the ALPHA-BNA rule.
        $this->upsert($source, 'num_autorisation', 'NUM_AUTO', [
            ['key' => 'trim'],
            ['key' => 'strip_prefix_chars', 'config' => ['chars' => ['B', 'b']]],
            ['key' => 'zero_pad', 'config' => ['length' => 6]],
        ], required: true, order: 0);

        // REFERENCE is the source's own internal reference — named
        // reference internally (not secondary_reference). It is a fixed
        // 9-digit code, but the xlsx sheet stores it as a numeric cell --
        // Excel/PhpSpreadsheet silently drops leading zeros on read, so it's
        // padded back even when it starts with 0s.
        $this->upsert($source, 'reference', 'REFERENCE', [
            ['key' => 'trim'],
            ['key' => 'zero_pad', 'config' => ['length' => 9]],
        ], order: 1);

        $this->upsert($source, 'amount', 'MONTANT_ENCAISS', [
            ['key' => 'trim'],
            ['key' => 'fixed_width_millimes'],
        ], required: true, order: 2);

        $this->upsert($source, 'date', 'DAT_ENC', [
            ['key' => 'date_parse', 'config' => ['format' => 'd/m/Y', 'output' => 'date']],
        ], required: true, order: 3);

        $this->upsert($source, 'canal', 'CANAL', [['key' => 'trim']], order: 4);
    }

    private function seedBna(): void
    {
        $source = Source::query()->where('code', 'BNA')->firstOrFail();

        // N° autorisation is a fixed 6-digit code, but the xlsx sheet stores
        // it as a numeric cell -- Excel/PhpSpreadsheet silently drops
        // leading zeros on read ("003512" -> "3512"), so it's padded back.
        // Named num_autorisation internally (not reference) per client spec.
        $this->upsert($source, 'num_autorisation', 'N° autorisation', [
            ['key' => 'trim'],
            ['key' => 'zero_pad', 'config' => ['length' => 6]],
        ], required: true, order: 0);

        $this->upsert($source, 'amount', 'Montant (TND)', [
            ['key' => 'trim'],
            ['key' => 'decimal_string_to_millimes', 'config' => ['decimals' => 3]],
        ], required: true, order: 1);

        $this->upsert($source, 'date', 'Date', [
            ['key' => 'date_parse', 'config' => ['format' => 'd/m/Y', 'output' => 'date']],
        ], required: true, order: 2);

        $this->upsert($source, 'status_raw', 'Type de la transaction', [['key' => 'trim']], order: 3);
    }

    private function seedWeb(): void
    {
        $source = Source::query()->where('code', 'WEB')->firstOrFail();

        // Client correction (2026-07): WEB is STEG's online payment portal
        // export. Per client spec, the reference is the 9 digits at the
        // RIGHT of the fused "session,reference" column (a single CSV column
        // literally named "session,reference", containing session+référence
        // in one cell). recu_paie (once its conditional b/B prefix is
        // stripped) becomes the auxiliary `secondary_reference` — it's the
        // cross-source matching key used against BNA's N° autorisation.
        $this->upsert($source, 'reference', 'session,reference', [
            ['key' => 'trim'],
            ['key' => 'right_chars', 'config' => ['length' => 9]],
        ], required: true, order: 0);

        // recu_paie is the cross-source matching key against BNA's
        // N° autorisation (WEB-BNA rule). Zero-padded to 6 to align with
        // BNA's zero-padded num_autorisation.
        $this->upsert($source, 'secondary_reference', 'recu_paie', [
            ['key' => 'trim'],
            ['key' => 'strip_prefix_chars', 'config' => ['chars' => ['B', 'b']]],
            ['key' => 'zero_pad', 'config' => ['length' => 6]],
        ], order: 1);

        $this->upsert($source, 'amount', 'montant', [
            ['key' => 'trim'],
            ['key' => 'fixed_width_millimes'],
        ], required: true, order: 2);

        // DATE_FORMAT(`date_au`, '%d%m%Y') has no known reconciliation role
        // and is intentionally left unmapped; date_paiement is the real
        // transaction date.
        $this->upsert($source, 'date', 'date_paiement', [
            ['key' => 'date_parse', 'config' => ['format' => 'Y-m-d H:i:s', 'output' => 'date']],
        ], required: true, order: 3);

        $this->upsert($source, 'datetime', 'date_paiement', [
            ['key' => 'date_parse', 'config' => ['format' => 'Y-m-d H:i:s', 'output' => 'datetime']],
        ], order: 4);
    }

    private function seedSmt(): void
    {
        $source = Source::query()->where('code', 'SMT')->firstOrFail();

        // Client correction (2026-07): per client spec, SMT keeps ONLY
        // date and amount — every other field (reference, secondary
        // reference, datetime, currency, status) is intentionally removed.
        // Matching against other sources is done on date + amount only.
        // The real file's bytes have literal '?' (0x3F) wherever an accented
        // character belongs -- verified neither UTF-8 nor CP1252 decoding
        // recovers the accents, so it isn't fixable on read; source_column
        // below MUST use this exact mangled form, not the grammatically
        // correct French text.
        $this->upsert($source, 'amount', 'Montant', [
            ['key' => 'trim'],
            ['key' => 'decimal_string_to_millimes', 'config' => ['decimals' => 3]],
        ], required: true, order: 0);

        // The column literally named "New Deposit date" in the current
        // export (not "Date", which is the auth request time, nor "New
        // Payment date", which precedes the deposit).
        $this->upsert($source, 'date', 'New Deposit date', [
            ['key' => 'date_parse', 'config' => ['format' => 'Y.m.d H:i:s', 'output' => 'date']],
        ], required: true, order: 1);
    }

    private function seedSteg(): void
    {
        $source = Source::query()->where('code', 'STEG')->firstOrFail();

        // STEG is the same file as WEB (client spec: "STEG (nommé aussi WEB)").
        // The reference is the 9 digits at the RIGHT of the fused
        // "session,reference" column; recu_paie becomes the auxiliary
        // `secondary_reference` (cross-source matching key against BNA's
        // N° autorisation).
        $this->upsert($source, 'reference', 'session,reference', [
            ['key' => 'trim'],
            ['key' => 'right_chars', 'config' => ['length' => 9]],
        ], required: true, order: 0);

        // STEG is the same file as WEB — recu_paie is the cross-source
        // matching key against BNA's N° autorisation. Zero-padded to 6.
        $this->upsert($source, 'secondary_reference', 'recu_paie', [
            ['key' => 'trim'],
            ['key' => 'strip_prefix_chars', 'config' => ['chars' => ['B', 'b']]],
            ['key' => 'zero_pad', 'config' => ['length' => 6]],
        ], order: 1);

        $this->upsert($source, 'amount', 'montant', [
            ['key' => 'trim'],
            ['key' => 'fixed_width_millimes'],
        ], required: true, order: 2);

        $this->upsert($source, 'date', 'date_paiement', [
            ['key' => 'date_parse', 'config' => ['format' => 'Y-m-d H:i:s', 'output' => 'date']],
        ], required: true, order: 3);

        $this->upsert($source, 'datetime', 'date_paiement', [
            ['key' => 'date_parse', 'config' => ['format' => 'Y-m-d H:i:s', 'output' => 'datetime']],
        ], order: 4);
    }

    /** @param array<int,array<string,mixed>> $transform */
    private function upsert(Source $source, string $targetField, string $sourceColumn, array $transform, bool $required = false, int $order = 0): void
    {
        SourceColumnMapping::query()->updateOrCreate(
            ['source_id' => $source->id, 'target_field' => $targetField],
            [
                'source_column' => $sourceColumn,
                'transform' => $transform,
                'is_required' => $required,
                'sort_order' => $order,
            ]
        );
    }
}
